language: php
cache:
    directories:
        - $HOME/.composer/cache/files
matrix:
    fast_finish: true
    include:
        - php: 7.4
install:
    - composer install -n
script:
    - composer test
